create table "public"."employees" (
    "id" uuid not null,
    "created_at" timestamp with time zone default now(),
    "first_name" text not null,
    "last_name" text not null,
    "manager" uuid,
    "role" text default 'contractor'::text
);


alter table "public"."employees" enable row level security;

create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "fk" bigint not null,
    "type" text not null,
    "read" boolean not null default false,
    "user" uuid,
    "description" text not null
);


alter table "public"."events" enable row level security;

create table "public"."newsfeed" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "headline" text not null,
    "body" text not null
);


alter table "public"."newsfeed" enable row level security;

CREATE UNIQUE INDEX employees_pkey ON public.employees USING btree (id);

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE UNIQUE INDEX newsfeed_pkey ON public.newsfeed USING btree (id);

alter table "public"."employees" add constraint "employees_pkey" PRIMARY KEY using index "employees_pkey";

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."newsfeed" add constraint "newsfeed_pkey" PRIMARY KEY using index "newsfeed_pkey";

alter table "public"."employees" add constraint "employees_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."employees" validate constraint "employees_id_fkey";

alter table "public"."employees" add constraint "employees_manager_fkey" FOREIGN KEY (manager) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."employees" validate constraint "employees_manager_fkey";

alter table "public"."events" add constraint "events_user_fkey" FOREIGN KEY ("user") REFERENCES employees(id) ON DELETE CASCADE not valid;

alter table "public"."events" validate constraint "events_user_fkey";



